#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cgts-mtce-common
Version  : 6a5e10492cf09b47463cd38d806c36386a459718
Release  : 1
URL      : https://github.com/openstack/stx-metal/archive/6a5e10492cf09b47463cd38d806c36386a459718.tar.gz
Source0  : https://github.com/openstack/stx-metal/archive/6a5e10492cf09b47463cd38d806c36386a459718.tar.gz
Summary  : Titanium Cloud Platform Common Node Maintenance Package
Group    : Development/Tools
License  : Apache-2.0
Requires: /bin/bash
Requires: /bin/sh
Requires: /bin/systemctl
Requires: /usr/bin/expect
Requires: dpkg
Requires: expect
Requires: fm-common >= 1.0
Requires: libc.so.6()(64bit)
Requires: libc.so.6(GLIBC_2.14)(64bit)
Requires: libc.so.6(GLIBC_2.2.5)(64bit)
Requires: libc.so.6(GLIBC_2.3)(64bit)
Requires: libc.so.6(GLIBC_2.4)(64bit)
Requires: libevent >= 2.0.21
Requires: libevent-2.0.so.5()(64bit)
Requires: libfmcommon.so.1()(64bit)
Requires: libgcc_s.so.1()(64bit)
Requires: libgcc_s.so.1(GCC_3.0)(64bit)
Requires: libjson-c.so.2()(64bit)
Requires: libm.so.6()(64bit)
Requires: libpthread.so.0()(64bit)
Requires: libpthread.so.0(GLIBC_2.2.5)(64bit)
Requires: librt.so.1()(64bit)
Requires: librt.so.1(GLIBC_2.2.5)(64bit)
Requires: librt.so.1(GLIBC_2.3.3)(64bit)
Requires: libssh2.so.1()(64bit)
Requires: libstdc++.so.6()(64bit)
Requires: libstdc++.so.6(CXXABI_1.3)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
Requires: libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
Requires: libuuid.so.1()(64bit)
Requires: python-rtslib
Requires: rtld(GNU_HASH)
Requires: time
Requires: util-linux
BuildRequires : cppcheck
BuildRequires : expect
BuildRequires : fm-common
BuildRequires : fm-common-dev
BuildRequires : fm-mgr
BuildRequires : json-c
BuildRequires : json-c-devel
BuildRequires : libevent
BuildRequires : libevent-devel
BuildRequires : libssh2
BuildRequires : libssh2-devel
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : pluggy
BuildRequires : postgresql
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : systemd-devel
BuildRequires : tox
BuildRequires : util-linux-dev
BuildRequires : virtualenv
Patch1: 0001-fix-warnings-being-treated-as-errors-in-mtce-common.patch

%description
agent/client daemons as well as the hardware and process monitor
             daemons, hardware watchdog process, resource and file system daemons
             as well as initialization and support files for each.

%package dev
Summary: dev components for the cgts-mtce-common package.
Group: Development
Provides: cgts-mtce-common-devel

%description dev
dev components for the cgts-mtce-common package.


%prep
%setup -q -n stx-metal-6a5e10492cf09b47463cd38d806c36386a459718
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538979037
pushd mtce-common/src
make  %{?_smp_mflags} MAJOR=${version%%.*} \
MINOR=${version##*.} \
build VER=${MINOR} VER_MJR=${MAJOR}
popd

%install
export SOURCE_DATE_EPOCH=1538979037
rm -rf %{buildroot}
pushd mtce-common/src
echo "Empty"
popd
## install_append content
%global subdir "mtce-common/src"
%global _sysconfdir '/usr/local/etc'
%global _buildsubdir %{subdir}
install -m 755 -d %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/daemon/libdaemon.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libcommon.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libthreadUtil.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libipmiUtil.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libpingUtil.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libnodeBase.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libregexUtil.a %{buildroot}%{_libdir}
install -m 644 -p -D %{_buildsubdir}/common/libhostUtil.a %{buildroot}%{_libdir}
install -m 755 -d %{buildroot}%{_includedir}
install -m 755 -d %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/fitCodes.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/logMacros.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/returnCodes.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeTimers.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/hostClass.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/httpUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/jsonUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/msgClass.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeBase.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeEvent.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeMacro.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nodeUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/timeUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 755 -d %{buildroot}%{_includedir}/mtce-daemon
install -m 644 -p -D %{_buildsubdir}/daemon/daemon_ini.h %{buildroot}%{_includedir}/mtce-daemon
install -m 644 -p -D %{_buildsubdir}/daemon/daemon_common.h %{buildroot}%{_includedir}/mtce-daemon
install -m 644 -p -D %{_buildsubdir}/daemon/daemon_option.h %{buildroot}%{_includedir}/mtce-daemon
install -m 644 -p -D %{_buildsubdir}/common/alarmUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/hostUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/ipmiUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/nlEvent.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/pingUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/regexUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/threadUtil.h %{buildroot}%{_includedir}/mtce-common
install -m 644 -p -D %{_buildsubdir}/common/tokenUtil.h %{buildroot}%{_includedir}/mtce-common
%clean
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/mtce-common/alarmUtil.h
/usr/include/mtce-common/fitCodes.h
/usr/include/mtce-common/hostClass.h
/usr/include/mtce-common/hostUtil.h
/usr/include/mtce-common/httpUtil.h
/usr/include/mtce-common/ipmiUtil.h
/usr/include/mtce-common/jsonUtil.h
/usr/include/mtce-common/logMacros.h
/usr/include/mtce-common/msgClass.h
/usr/include/mtce-common/nlEvent.h
/usr/include/mtce-common/nodeBase.h
/usr/include/mtce-common/nodeEvent.h
/usr/include/mtce-common/nodeMacro.h
/usr/include/mtce-common/nodeTimers.h
/usr/include/mtce-common/nodeUtil.h
/usr/include/mtce-common/pingUtil.h
/usr/include/mtce-common/regexUtil.h
/usr/include/mtce-common/returnCodes.h
/usr/include/mtce-common/threadUtil.h
/usr/include/mtce-common/timeUtil.h
/usr/include/mtce-common/tokenUtil.h
/usr/include/mtce-daemon/daemon_common.h
/usr/include/mtce-daemon/daemon_ini.h
/usr/include/mtce-daemon/daemon_option.h
/usr/lib64/*.a
